# Validate for errors with http://www.yamllint.com/
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
      ignore_warnings: true
    checks:
      Generic PHP LowerCaseConstant Found:
        enabled: false
      Squiz Commenting InlineComment InvalidEndChar:
        enabled: false
      WordPress PHP YodaConditions:
        enabled: false
      WordPress Arrays ArrayKeySpacingRestrictions SpacesAroundArrayKeys:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
ratings:
  paths:
    - "**.php"
exclude_paths:
  - "**/assets/**/*"